### ISSUE TITLE
Installation failure: not able to backup database

### ISSUE THREAD

**Issue by CarolinaFernandez** [fp7-ofelia/ocf#104]
When upgrading (vt_manager module) from 0.21.1 to 0.4...
## 

>  Syncing Database...  

/usr/lib/pymodules/python2.6/registration/models.py:4: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  import sha
**Project signature has changed - an evolution is required
No fixtures found.**

>  Evolving Database schema...  
> /usr/lib/pymodules/python2.6/registration/models.py:4: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
>   import sha

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_manager(settingsLoader)
  File "/usr/lib/pymodules/python2.6/django/core/management/**init**.py", line 438, in execute_manager
    utility.execute()
  File "/usr/lib/pymodules/python2.6/django/core/management/**init**.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/pymodules/python2.6/django/core/management/base.py", line 191, in run_from_argv
    self.execute(*args, **options.**dict**)
  File "/usr/lib/pymodules/python2.6/django/core/management/base.py", line 220, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.6/dist-packages/django_evolution-0.6.2-py2.6.egg/django_evolution/management/commands/evolve.py", line 60, in handle
    self.evolve(*app_labels, **options)
  File "/usr/local/lib/python2.6/dist-packages/django_evolution-0.6.2-py2.6.egg/django_evolution/management/commands/evolve.py", line 140, in evolve
    database))
  File "/usr/local/lib/python2.6/dist-packages/django_evolution-0.6.2-py2.6.egg/django_evolution/mutations.py", line 650, in mutate
    model = MockModel(proj_sig, app_label, self.model_name, model_sig)
  File "/usr/local/lib/python2.6/dist-packages/django_evolution-0.6.2-py2.6.egg/django_evolution/mutations.py", line 200, in **init**
    self._meta.setup_fields(self, stub)
  File "/usr/local/lib/python2.6/dist-packages/django_evolution-0.6.2-py2.6.egg/django_evolution/mutations.py", line 146, in setup_fields
    field_sig, model)
  File "/usr/local/lib/python2.6/dist-packages/django_evolution-0.6.2-py2.6.egg/django_evolution/mutations.py", line 33, in create_field
    related_model_sig = proj_sig[related_app_name][related_model_name]
**KeyError: 'MessageDB'
FATAL ERROR: Could not evolve database...**

 info#  Using default rollback module...  
It seems something went wrong.. Now you will be able to rollback to the previous state of the filsystem and database. Alternatevily you can try to solve the problem manually, avoiding the rollback mechanism. Do you want to rollback now?. Do you confirm (Y/N)?
y
Restoring files...
Restoring database...
mysql -e "drop database vtm; CREATE DATABASE vtm;GRANT ALL ON vtm . \* TO 'expedient'@'localhost';" --user='expedient' --password='<expedient_password>' vtm < /<ofelia_path>/vt_manager/bin/rescue/11:41-311212#4938/dbdump.sql
**ERROR 1044 (42000) at line 1: Access denied for user 'expedient'@'localhost' to database 'vtm'
FATAL ERROR: Could not restore database. Please take into account that previous state including DB state is in /<ofelia_path>/vt_manager/bin/rescue/11:41-311212#4938**

**Comment by CarolinaFernandez** [comment]
2nd error (restoration of database) should not attempt to grant permissions on the same user under which the MySQL commands are running.

Also, syntax does not seem correct; because when executing:

> mysql -e "drop database vtm; CREATE DATABASE vtm; GRANT ALL ON vtm . \* TO 'expedient'@'localhost';" --user='root' --password='<root_password>' vtm < "/<ofelia_path>/vt_manager/bin/rescue/11:41-311212#4938/dbdump.sql"

the database is still empty.

**Instead, this should be:**

> mysql -e "drop database vtm; CREATE DATABASE vtm; GRANT ALL ON vtm . \* TO 'expedient'@'localhost';" --user='root' --password='<root_password>' && mysql --user='expedient' --password='<expedient_password>' vtm < "/<ofelia_path>/vt_manager/bin/rescue/11:41-311212#4938/dbdump.sql"

**and consequently the MySQL root password shall be asked to the user.**

### Solution:

**Affected files:**
`<module_name>/expedient/bin/versions/default/upgrade/tools/sqlRestore.py`

> ```
> import os
> import sys
> from os.path import dirname, join
> from django.conf import * 
> #configobj
> try:
>     from configobj import ConfigObj
> except:
>     #FIXME: ugly
>     os.system("apt-get update && apt-get install python-configobj -y")
> from configobj import ConfigObj
> cfg = ConfigObj(sys.argv[1]+".cfg")
> section = cfg['General']
> #Dropping the database and recreating
> #Setting MySQL password to dump DB
> mysql_pass = ""
> import getpass
> while mysql_pass == "":
>     #mysql_pass = raw_input('Please enter MySQL root password: ');
>     mysql_pass = getpass.getpass("Please enter MySQL root password: ")
> #Preparing command
> command =''
> mysql_user = "root"
> command += " --user='" + mysql_user + "'"
> if mysql_pass != "":
>     command+=" --password='" + mysql_pass + "'"
> if section["host"] != "":
>     command+=" --host=" + section["host"]
> if section["port"] != "":
>     command+=" --port=" + section["port"]
> if section["host"] == "":
>     host="localhost"
> else:
>     host=section["host"]
> importDB = "mysql " + command + " " + section["database"]+ " < " + "\"" + sys.argv[1] + "\""
> dropDB="mysql -e \"drop database " + section["database"] + "; CREATE DATABASE " + section["database"] + "; GRANT ALL ON " + section["database"] + ".* TO '" + section["user"] + "'@'" + host + "';\"" + command
> dropDB += " && " + importDB
> print dropDB
> if os.system(dropDB)>0:
>     sys.exit(1)
> print importDB
> sys.exit(os.system(importDB))
> ```

**Comment by CarolinaFernandez** [comment]
Fixed.

The mysql command that grants permissions will be run under "root" user, and the user will be prompted for the password.

New code ( **sqlRestore.py** ):

> import os
> import sys
> from os.path import dirname, join
> from django.conf import \* 
> 
> #configobj
> try:
>     from configobj import ConfigObj
> except:
>     #FIXME: ugly
>     os.system("apt-get update && apt-get install python-configobj -y")
>     from configobj import ConfigObj
> 
> cfg = ConfigObj(sys.argv[1]+".cfg")
> 
> section = cfg['General']
> 
> #Droping the database and recreating
> 
> #Preparing command
> command = ""
> # User must be 'root' in order to successfully backup the database.
> command_root = " --user='root' --password"
> 
> if section["user"] != "":
>     command+=" --user='"+ section["user"]+"'"
> if section["password"] != "":
>     command+=" --password='"+ section["password"]+"'"
> if section["host"] != "":
>     command += " --host=" + section["host"]
>     command_root += " --host=" + section["host"]
> if section["port"] != "":
>     command +=" --port=" + section["port"]
>     command_root +=" --port=" + section["port"]
> 
> command += " " + section["database"] + " < " + sys.argv[1]
> command_root += " " + section["database"] + " < " + sys.argv[1]
> 
> if section["host"] == "":
>         host = "localhost"
> else:
>         host = section["host"]
> 
> # Island Manager will be prompted to enter the root's password for the backup
> dropDB = "mysql -e \"drop database " + section["database"] + "; create database " + section["database"] + "; grant all on " + section["database"] + ".\* to '" + section["user"] + "'@'" + host + "';\"" + command_root
> print dropDB
> 
> print "\nPlease input your MySQL root password in order to perform a backup of %s..." % str(section["database"])
> if os.system(dropDB)>0:
>         sys.exit(1)
> 
> importDB = "mysql" + command + " < " + sys.argv[1]
> print importDB
> sys.exit(os.system(importDB))
