### ISSUE TITLE
Exception booking flowspace in simple mode

### ISSUE THREAD

**Issue by CarolinaFernandez** [fp7-ofelia/ocf#155]
When in preproduction and trying to book a flowspace for a slice through the simple mode, the OCF crashes:

Trace for v0.4.3 ( **note**: paths to plugin change in 0.5)

> [Tue May 07 08:57:48 2013] [error] [client 147.83.206.82] Traceback (most recent call last):
> [Tue May 07 08:57:48 2013] [error] [client 147.83.206.82]   File "/usr/lib/pymodules/python2.6/django/core/handlers/wsgi.py", line 241, in **call**
> [Tue May 07 08:57:48 2013] [error] [client 147.83.206.82]     response = self.get_response(request)
> [Tue May 07 08:57:48 2013] [error] [client 147.83.206.82]   File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 141, in get_response
> [Tue May 07 08:57:48 2013] [error] [client 147.83.206.82]     return self.handle_uncaught_exception(request, resolver, sys.exc_info())
> [Tue May 07 08:57:48 2013] [error] [client 147.83.206.82]   File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 100, in get_response
> [Tue May 07 08:57:48 2013] [error] [client 147.83.206.82]     response = callback(request, _callback_args, *_callback_kwargs)
> [Tue May 07 08:57:48 2013] [error] [client 147.83.206.82]   File "/opt/ofelia/expedient/src/wsgi/expedient/clearinghouse/../../../python/expedient/ui/html/views.py", line 516, in bookOpenflow
> [Tue May 07 08:57:48 2013] [error] [client 147.83.206.82]     return flowspace(request, slice_id, fsmode, free_vlan, alertMessage)
> [Tue May 07 08:57:48 2013] [error] [client 147.83.206.82]   File "/opt/ofelia/expedient/src/wsgi/expedient/clearinghouse/../../../python/expedient/ui/html/views.py", line 673, in flowspace
> [Tue May 07 08:57:48 2013] [error] [client 147.83.206.82]     "fsformset": formset,
> [Tue May 07 08:57:48 2013] [error] [client 147.83.206.82] UnboundLocalError: local variable 'formset' referenced before assignment

The problem is that a few lines before 

```
    return simple.direct_to_template(
        ...
            "fsformset": formset,
```

this is made:

```
            try:
                create_simple_slice_vlan_based(free_vlan[0], slice)
                continue_to_start_slice = True
            except Exception as e:
                #continue_to_start_slice flag will deal with this
                pass
```

and `create_simple_slice_vlan_based` returns an empty list (meaning that **all** VLANs are used, at least in preproduction), giving and exception and never setting `continue_to_start_slice` to True.

**Comment by CarolinaFernandez** [comment]
Fixed. The real problem was that, in the current version, the [`openflow view's plugin`](https://github.com/fp7-ofelia/ocf/blob/OCF-v0.5/expedient/src/python/plugins/openflow/plugin/views.py) (as of first 0.5 release) there is the following:

```
def flowspace(request, slice_id, fsmode = 'advanced', free_vlan = None, alertMessage=""):
   ...
    if request.method == "POST":
        continue_to_start_slice = False
        if fsmode == 'advanced':
            formset = FSFormSet(
                request.POST,
                queryset=FlowSpaceRule.objects.filter(
                    slivers__slice=slice).distinct(),
            )
            if formset.is_valid():
                formset.save()
                continue_to_start_slice = True
        elif fsmode == 'simple':
            #create a simple flowspacerule containing only the vlans tags and the OF ports
            try:
                create_simple_slice_vlan_based(free_vlan[0], slice)
                continue_to_start_slice = True
            except Exception as e:
                #continue_to_start_slice flag will deal with this
                pass
        else:
             formset = FSFormSet(
                 queryset=FlowSpaceRule.objects.filter(
                     slivers__slice=slice).distinct(),
             )
```

when the try/except fails and the variable `continue_to_start_slice` is not set to True, execution won't enter the latter block of code to get back to the slice detail page and will try to access the "advanced" mode without setting first the `formset`.

One solution is to set a default `formset` and removing the latest "else":

```
    if request.method == "POST":
        continue_to_start_slice = False
        # Default formset
        formset = FSFormSet(
            queryset=FlowSpaceRule.objects.filter(
                slivers__slice=slice).distinct(),
        )
```
