### ISSUE TITLE
Missing settings for agent

### ISSUE THREAD

**Issue by CarolinaFernandez** [fp7-ofelia/ocf#162]
Agent's log showed an error with a missing setting. Not a big issue, but should be solved if monitoring is to be done as expected.

```
libvir: Xen error : Domain not found: xenUnifiedDomainLookupByName
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/libvirt.py", line 1953, in dispatchDomainEventLifecycleCallback
    cb(self, virDomain(self, _obj=dom), event, detail, opaque)
  File "/opt/ofelia/oxa/repository/vt_manager/src/python/agent/monitoring/LibvirtMonitoring.py", line 451, in LifeCycleEventCallbacks
    raise e
NameError: global name 'XMLRPC_USER' is not defined
```

**Comment by CarolinaFernandez** [comment]
Looking to the agent settings there were 4 settings from the VT manager that were needed to perform the callbacks. These settings are now added to the `mySettings-example.py` file and will also be added by ofver if not in the settings file.
