### ISSUE TITLE
Permission problem when agg status is updated

### ISSUE THREAD

**Issue by CarolinaFernandez** [fp7-ofelia/ocf#164]
The error trace is as follows:

```
[Thu Jun 13 04:33:17 2013] [error] -3290222034630458481
[Thu Jun 13 04:33:17 2013] [error] Same HASH, no changes in resources
[Thu Jun 13 04:33:18 2013] [error] -1125493255124132145
[Thu Jun 13 04:33:18 2013] [error] Same HASH, no changes in resources
[Thu Jun 13 04:33:45 2013] [error] Exception while pinging server: <ProtocolError for clearinghouse:0f3lia0p3nFl0w@10.216.16.4:8443/xmlrpc/xmlrpc/: 500 Internal Server Error>
[Thu Jun 13 04:33:45 2013] [error] Traceback (most recent call last):
[Thu Jun 13 04:33:45 2013] [error]   File "/opt/ofelia/expedient/src/wsgi/expedient/clearinghouse/../../../python/expedient/common/xmlrpc_serverproxy/models.py", line 178, in is_available
[Thu Jun 13 04:33:45 2013] [error]     ret = self.ping("PING")
[Thu Jun 13 04:33:45 2013] [error]   File "/opt/ofelia/expedient/src/wsgi/expedient/clearinghouse/../../../python/expedient/common/xmlrpc_serverproxy/models.py", line 173, in ping
[Thu Jun 13 04:33:45 2013] [error]     return self.proxy.ping(data)
[Thu Jun 13 04:33:45 2013] [error]   File "/usr/lib/python2.6/xmlrpclib.py", line 1199, in __call__
[Thu Jun 13 04:33:45 2013] [error]     return self.__send(self.__name, args)
[Thu Jun 13 04:33:45 2013] [error]   File "/usr/lib/python2.6/xmlrpclib.py", line 1489, in __request
[Thu Jun 13 04:33:45 2013] [error]     verbose=self.__verbose
[Thu Jun 13 04:33:45 2013] [error]   File "/usr/lib/pymodules/python2.6/M2Crypto/m2xmlrpclib.py", line 60, in request
[Thu Jun 13 04:33:45 2013] [error]     headers
[Thu Jun 13 04:33:45 2013] [error] ProtocolError: <ProtocolError for clearinghouse:0f3lia0p3nFl0w@10.216.16.4:8443/xmlrpc/xmlrpc/: 500 Internal Server Error>
[Thu Jun 13 04:33:45 2013] [error] 
[Thu Jun 13 04:33:45 2013] [error] 
[Thu Jun 13 04:33:45 2013] [error] 
[Thu Jun 13 04:33:45 2013] [error] 
[Thu Jun 13 04:33:45 2013] [error] 
[Thu Jun 13 04:33:45 2013] [error] 
[Thu Jun 13 04:33:45 2013] [error] 
[Thu Jun 13 04:33:45 2013] [error] 
[Thu Jun 13 04:33:45 2013] [error] 
[Thu Jun 13 04:33:45 2013] [error] 
[Thu Jun 13 04:33:45 2013] [error] 
[Thu Jun 13 04:33:45 2013] [error] 
[Thu Jun 13 04:33:45 2013] [error] saving aggregate status
[Thu Jun 13 04:33:45 2013] [error] 
[Thu Jun 13 04:33:45 2013] [error] 
[Thu Jun 13 04:33:45 2013] [error] 
[Thu Jun 13 04:33:45 2013] [error] 
[Thu Jun 13 04:33:45 2013] [error] 
[Thu Jun 13 04:33:45 2013] [error] 
[Thu Jun 13 04:33:45 2013] [error] 
[Thu Jun 13 04:33:45 2013] [error] 
[Thu Jun 13 04:33:45 2013] [error] 
[Thu Jun 13 04:33:45 2013] [error] 
[Thu Jun 13 04:33:45 2013] [error] 
[Thu Jun 13 04:33:45 2013] [error] 2013-06-13 04:33:45,414:AggregateViews:ERROR
[Thu Jun 13 04:33:45 2013] [error]     /opt/ofelia/expedient/src/wsgi/expedient/clearinghouse/../../../python/expedient/clearinghouse/aggregate/views.py:159
[Thu Jun 13 04:33:45 2013] [error]     **** Traceback (most recent call last):
[Thu Jun 13 04:33:45 2013] [error]   File "/opt/ofelia/expedient/src/wsgi/expedient/clearinghouse/../../../python/expedient/clearinghouse/aggregate/views.py", line 153, in status_img_url
[Thu Jun 13 04:33:45 2013] [error]     aggregate.save()
[Thu Jun 13 04:33:45 2013] [error]   File "/opt/ofelia/expedient/src/wsgi/expedient/clearinghouse/../../../python/expedient/common/permissions/utils.py", line 176, in save
[Thu Jun 13 04:33:45 2013] [error]     must_have_permission(permittee_kw, self, edit_perm)
[Thu Jun 13 04:33:45 2013] [error]   File "/opt/ofelia/expedient/src/wsgi/expedient/clearinghouse/../../../python/expedient/common/permissions/shortcuts.py", line 88, in must_have_permission
[Thu Jun 13 04:33:45 2013] [error]     permittee, allow_redirect=allow_redirect)
[Thu Jun 13 04:33:45 2013] [error] PermissionDenied: Permission 'can_edit_aggregate' was not found for permittee 'carolina' for target object 'Aggregate TUB OF AM'
```

Nobody can access Expedient after this kind of stuff. This is happening in production servers.

This was **replicated** by adding some AMs from another island to a given slice. There is a time where **aggregate status is checked and saved**. This works fine for a super user, which has the `can_edit_aggregate` permission; but not for a normal user.

To check the problem looking to the code:
1. [`aggregate/views.py`](https://github.com/fp7-ofelia/ocf/blob/ofelia.stable/expedient/src/python/expedient/clearinghouse/aggregate/views.py#L152)
2. There is a method that overwrites the Aggregate `save` method and uses the `permissions_save_override` in [`permissions/utils.py`](https://github.com/fp7-ofelia/ocf/blob/ofelia.stable/expedient/src/python/expedient/common/permissions/utils.py#L176). Here, the current user is obtained and it is checked if that person has the specific permission.

**Comment by CarolinaFernandez** [comment]
A starting direction would be to modify [`aggregate/views.py`](https://github.com/fp7-ofelia/ocf/blob/ofelia.stable/expedient/src/python/expedient/clearinghouse/aggregate/views.py) as follows, so **the AM status shall be updated only when a root user is checking the Expedient**. This is not efficient, but it seems better than giving or ignoring the `can_edit_aggregate` for a normal user.

```
from django.contrib.auth.models import User
from expedient.common.permissions.models import ExpedientPermission

(...)

def status_img_url(request, agg_id):
    """Get the url for the status image of the aggregate"""

    aggregate = get_object_or_404(Aggregate, pk=agg_id)

    success = HttpResponse(reverse("img_media", args=["active.png"]))
    fail = HttpResponse(reverse("img_media", args=["inactive.png"]))

    try:
        # Check aggregate status and update model if:
        # * request.user has permission to edit aggregate
        # * aggregate status has changed
        agg_status = aggregate.as_leaf_class().check_status()
#        if request.user in User.objects.filter(is_superuser=True):
        if request.user.has_perm(ExpedientPermission.objects.get(name="can_edit_aggregate")):
            if agg_status != aggregate.available:
                aggregate.available = agg_status
                aggregate.save()
        if agg_status:
            return success
        else:
            return fail
    except:
        logger.error(traceback.format_exc())
        return fail
```

However, the slices that provoked this error seem to be still not accessible. We must investigate what is really happening here.

**Comment by CarolinaFernandez** [comment]
This seems to have nothing to do now. That code has been deleted in `ofelia.development` branch, since the `expedient.clearinghouse.monitoring.AggregateMonitoringThread` class already takes care of periodically checking the AM state and does not need any extra permission check.
