### ISSUE TITLE
Failed import in background daemon for expiration

### ISSUE THREAD

**Issue by CarolinaFernandez** [fp7-ofelia/ocf#205]
Related to SFA API in Opt-in manager. Import is OK, detected to be a circular dependency.

```
[Mon Feb 10 02:42:04 2014] [error] mod_wsgi (pid=4704): Target WSGI script '/opt/ofelia/optin_manager/src/wsgi/openflow/optin_manager/mon.wsgi' cannot be loaded as Python module.
[Mon Feb 10 02:42:04 2014] [error] mod_wsgi (pid=4704): Exception occurred processing WSGI script '/opt/ofelia/optin_manager/src/wsgi/openflow/optin_manager/mon.wsgi'.
[Mon Feb 10 02:42:04 2014] [error] Traceback (most recent call last):
[Mon Feb 10 02:42:04 2014] [error]   File "/opt/ofelia/optin_manager/src/wsgi/openflow/optin_manager/mon.wsgi", line 16, in <module>
[Mon Feb 10 02:42:04 2014] [error]     from openflow.optin_manager.monitoring.background_expiration_monitoring import BackgroundExpirationMonitoring
[Mon Feb 10 02:42:04 2014] [error]   File "/opt/ofelia/optin_manager/src/wsgi/openflow/optin_manager/../../../python/openflow/optin_manager/monitoring/background_expiration_monitoring.py", line 1, in <module>
[Mon Feb 10 02:42:04 2014] [error]     from openflow.optin_manager.sfa.openflow_utils.expiration_manager import ExpirationManager
[Mon Feb 10 02:42:04 2014] [error]   File "/opt/ofelia/optin_manager/src/wsgi/openflow/optin_manager/../../../python/openflow/optin_manager/sfa/openflow_utils/expiration_manager.py", line 5, in <module>
[Mon Feb 10 02:42:04 2014] [error]     from openflow.optin_manager.sfa.drivers.OFSfaDriver import OFSfaDriver
[Mon Feb 10 02:42:04 2014] [error]   File "/opt/ofelia/optin_manager/src/wsgi/openflow/optin_manager/../../../python/openflow/optin_manager/sfa/drivers/OFSfaDriver.py", line 16, in <module>
[Mon Feb 10 02:42:04 2014] [error]     from openflow.optin_manager.sfa.drivers.OFAggregate import OFAggregate
[Mon Feb 10 02:42:04 2014] [error]   File "/opt/ofelia/optin_manager/src/wsgi/openflow/optin_manager/../../../python/openflow/optin_manager/sfa/drivers/OFAggregate.py", line 6, in <module>
[Mon Feb 10 02:42:04 2014] [error]     from openflow.optin_manager.sfa.openflow_utils.foam_rspec_lib import getAdvertisement, getManifest
[Mon Feb 10 02:42:04 2014] [error]   File "/opt/ofelia/optin_manager/src/wsgi/openflow/optin_manager/../../../python/openflow/optin_manager/sfa/openflow_utils/foam_rspec_lib.py", line 10, in <module>
[Mon Feb 10 02:42:04 2014] [error]     from openflow.optin_manager.xmlrpc_server.models import CallBackServerProxy, FVServerProxy
[Mon Feb 10 02:42:04 2014] [error]   File "/opt/ofelia/optin_manager/src/wsgi/openflow/optin_manager/../../../python/openflow/optin_manager/xmlrpc_server/__init__.py", line 3, in <module>
[Mon Feb 10 02:42:04 2014] [error]     from sfa_api import *
[Mon Feb 10 02:42:04 2014] [error]   File "/opt/ofelia/optin_manager/src/wsgi/openflow/optin_manager/../../../python/openflow/optin_manager/xmlrpc_server/sfa_api.py", line 12, in <module>
[Mon Feb 10 02:42:04 2014] [error]     from openflow.optin_manager.sfa.managers.AggregateManager import AggregateManager
[Mon Feb 10 02:42:04 2014] [error]   File "/opt/ofelia/optin_manager/src/wsgi/openflow/optin_manager/../../../python/openflow/optin_manager/sfa/managers/AggregateManager.py", line 6, in <module>
[Mon Feb 10 02:42:04 2014] [error]     from openflow.optin_manager.sfa.drivers.OFSfaDriver import OFSfaDriver
[Mon Feb 10 02:42:04 2014] [error] ImportError: cannot import name OFSfaDriver
```

**Comment by OscarMoya** [comment]
Solved. There were some typos in mon.wsgi and Expiration Manager classes and a circular dependency problem caused by  ExpirationManager.

The typos were corrected and the import put inside ExpirationManager's method.
