### ISSUE TITLE
Failure on ListActiveVMs call

### ISSUE THREAD

**Issue by OscarMoya** [fp7-ofelia/ocf#207]
There is an error when agent tries to send the ListActiveVMs response to VMMAnager.

The traceback is:

```
[Mon Feb 24 05:15:24 2014] [error] [client 10.216.140.4] mod_wsgi (pid=10898): Exception occurred processing WSGI script '/opt/ofelia/vt_manager/src/wsgi/vt_manager/django.wsgi'.
[Mon Feb 24 05:15:24 2014] [error] [client 10.216.140.4] Traceback (most recent call last):
[Mon Feb 24 05:15:24 2014] [error] [client 10.216.140.4]   File "/usr/lib/pymodules/python2.6/django/core/handlers/wsgi.py", line 241, in __call__
[Mon Feb 24 05:15:24 2014] [error] [client 10.216.140.4]     response = self.get_response(request)
[Mon Feb 24 05:15:24 2014] [error] [client 10.216.140.4]   File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 141, in get_response
[Mon Feb 24 05:15:24 2014] [error] ----------------------->FAILED!!
[Mon Feb 24 05:15:24 2014] [error] [client 10.216.140.4]     return self.handle_uncaught_exception(request, resolver, sys.exc_info())
[Mon Feb 24 05:15:24 2014] [error] [client 10.216.140.4]   File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 100, in get_response
[Mon Feb 24 05:15:24 2014] [error] [client 10.216.140.4]     response = callback(request, *callback_args, **callback_kwargs)
[Mon Feb 24 05:15:24 2014] [error] [client 10.216.140.4]   File "/usr/lib/pymodules/python2.6/django/views/decorators/csrf.py", line 23, in wrapped_view
[Mon Feb 24 05:15:24 2014] [error] [client 10.216.140.4]     resp = view_func(*args, **kwargs)
[Mon Feb 24 05:15:24 2014] [error] [client 10.216.140.4]   File "/usr/lib/pymodules/python2.6/django/views/decorators/csrf.py", line 36, in wrapped_view
[Mon Feb 24 05:15:24 2014] [error] [client 10.216.140.4]     return view_func(*args, **kwargs)
[Mon Feb 24 05:15:24 2014] [error] [client 10.216.140.4]   File "/opt/ofelia/vt_manager/src/wsgi/vt_manager/../../python/vt_manager/common/rpc4django/views.py", line 154, in serve_rpc_request
[Mon Feb 24 05:15:24 2014] [error] [client 10.216.140.4]     if request.method == "POST" and len(request.POST) > 0:
[Mon Feb 24 05:15:24 2014] [error] [client 10.216.140.4]   File "/usr/lib/pymodules/python2.6/django/core/handlers/wsgi.py", line 171, in _get_post
[Mon Feb 24 05:15:24 2014] [error] [client 10.216.140.4]     self._load_post_and_files()
[Mon Feb 24 05:15:24 2014] [error] [client 10.216.140.4]   File "/usr/lib/pymodules/python2.6/django/core/handlers/wsgi.py", line 151, in _load_post_and_files
[Mon Feb 24 05:15:24 2014] [error] [client 10.216.140.4]     self._post, self._files = http.QueryDict(self.raw_post_data, encoding=self._encoding), datastructures.MultiValueDict()
[Mon Feb 24 05:15:24 2014] [error] [client 10.216.140.4]   File "/usr/lib/pymodules/python2.6/django/core/handlers/wsgi.py", line 205, in _get_raw_post_data
[Mon Feb 24 05:15:24 2014] [error] [client 10.216.140.4]     size=content_length)
[Mon Feb 24 05:15:24 2014] [error] [client 10.216.140.4]   File "/usr/lib/pymodules/python2.6/django/core/handlers/wsgi.py", line 69, in safe_copyfileobj
[Mon Feb 24 05:15:24 2014] [error] [client 10.216.140.4]     buf = fsrc.read(min(length, size))
[Mon Feb 24 05:15:24 2014] [error] [client 10.216.140.4] IOError: request data read error
```

This error does not update the status of the VMs if there is a failure on the VTServer.

**Comment by OscarMoya** [comment]
Solved. The problem was in file `ofelia/vt_manager/src/python/agent/utils/vtRspecInterfece`.In commit fdf8a3d398ee14d0f129b778af7da90c943cf25c. There was an update of this file. The original file had some lines commented in `parse()`, `parseString()`, and `parseLiteral()` due to these methods construct the `rspec` tag in a wrong way and made collide the current empty xml files that we are using to construct de Monitoring/provisioning messages.
