### ISSUE TITLE
pypelib is not installed automatically by expedient module

### ISSUE THREAD

**Issue by gandroulidakis** [fp7-ofelia/ocf#77]
During the installation of expedient, there is an error after settings configuration phase, which is due to the fact that pypelib is not automatically installed.

Output from the installation:

Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    main()
  File "manage.py", line 10, in main
    execute_manager(settings)
  File "/usr/lib/pymodules/python2.6/django/core/management/**init**.py", line 438, in execute_manager
    utility.execute()
  File "/usr/lib/pymodules/python2.6/django/core/management/**init**.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/pymodules/python2.6/django/core/management/base.py", line 191, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/usr/lib/pymodules/python2.6/django/core/management/base.py", line 219, in execute
    self.validate()
  File "/usr/lib/pymodules/python2.6/django/core/management/base.py", line 249, in validate
    num_errors = get_validation_errors(s, app)
  File "/usr/lib/pymodules/python2.6/django/core/management/validation.py", line 28, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/usr/lib/pymodules/python2.6/django/db/models/loading.py", line 146, in get_app_errors
    self._populate()
  File "/usr/lib/pymodules/python2.6/django/db/models/loading.py", line 61, in _populate
    self.load_app(app_name, True)
  File "/usr/lib/pymodules/python2.6/django/db/models/loading.py", line 76, in load_app
    app_module = import_module(app_name)
  File "/usr/lib/pymodules/python2.6/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "../../vt_plugin/communication/**init**.py", line 1, in <module>
    from southCommInterface import *
  File "../../vt_plugin/communication/southCommInterface.py", line 1, in <module>
    from vt_manager.communication.utils.XmlHelper import *
  File "../../expedient/clearinghouse/defaultsettings/../../../../../../vt_manager/src/python/vt_manager/communication/**init**.py", line 9, in <module>
    from southCommInterface import *
  File "../../expedient/clearinghouse/defaultsettings/../../../../../../vt_manager/src/python/vt_manager/communication/southCommInterface.py", line 9, in <module>
    from vt_manager.controller.dispatchers.xmlrpc.DispatcherLauncher import DispatcherLauncher
  File "../../expedient/clearinghouse/defaultsettings/../../../../../../vt_manager/src/python/vt_manager/controller/dispatchers/xmlrpc/DispatcherLauncher.py", line 4, in <module>
    from vt_manager.controller.dispatchers.xmlrpc.ProvisioningDispatcher import ProvisioningDispatcher
  File "../../expedient/clearinghouse/defaultsettings/../../../../../../vt_manager/src/python/vt_manager/controller/dispatchers/xmlrpc/ProvisioningDispatcher.py", line 12, in <module>
    from vt_manager.controller.policies.RuleTableManager import RuleTableManager
  File "../../expedient/clearinghouse/defaultsettings/../../../../../../vt_manager/src/python/vt_manager/controller/policies/RuleTableManager.py", line 1, in <module>
    from pypelib.RuleTable import RuleTable
ImportError: No module named pypelib.RuleTable
FATAL ERROR: Could not synchronize database using manage.py...

**Comment by CarolinaFernandez** [comment]
First of all: thanks you for your participation in the OCF issue tracker, Georgios :)

The issue has been fixed and will be released within version 0.3.1 -- maybe even before.

The explanation: there is a import in the Expedient that refers to the VT Manager.

This first import happens in the file `expedient/src/python/vt_plugin/communication/southCommInterface.py`; and after that there may be a chain of dependencies until the "pypelib" classes are imported.

The dependency for the pyPElib package had been previously observed for the VT manager installation, but we didn't take this dependency into account for the Expedient module. Now it is.
