### ISSUE TITLE
Flowvisor does not push rules from slices with long Slice id

### ISSUE THREAD

**Issue by msune** [fp7-ofelia/ocf#88]
Flowvisor does not push rules from slices with long Slice ids:

e.g.: Slice=Data_plane_testing_slice_ID__openflow_geant_net_3:4

This might be a bug on FV or in exception handling of Optin (probably the former). Needs to be circumvented in any case

**Comment by lbergesio** [comment]
It is possible to add slices with (in principle) any name manually via fvctl, included the name in the example. 
Tested with OCF it also works, rules are pushed, see:
rule 2: FlowEntry[dpid=[00:00:00:00:00:00:00:0a],ruleMatch=[OFMatch[in_port=2,dl_vlan=0x1]],actionsList=[Slice:Data_plane_testing_slice_ID__openflow_geant_net_ID__192_168_254_193_15=4],id=[1509],priority=[5996000],]

Was the "3:4" in the original name of the slice? In the new version the character ": "is not  allowed. Maybe this is the reason.

**Comment by lbergesio** [comment]
Not sure if this is the problem, but in principle it is not possible to have an slice in the fv which name contains ":" due to the method get_fv_slice_name definition itself:
opts/models.py, class Experiment:
<code>
def get_fv_slice_name(self):
        s = "%s ID: %s" % (self.slice_name, self.slice_id)
        return s.replace(".", "_").replace(":", "_").replace("=", "_").replace(" ", "_").replace("'","_")
</code>

**Comment by lbergesio** [comment]
There is a comment in the previous method's definition in OPTIN:
 # TODO: takeout the replacement when Rob fixes the . escaping in FV

When creating a slice with name Data_plane_testing_slice_ID__openflow_geant_net_ID__192_168_254_193_15:4 there is no problem, but when triying to delete it:
<code>
OfeliaSDKr1:~# fvctl deleteSlice Data_plane_testing_slice_ID__openflow_geant_net_ID__192_168_254_193_15.4
Enter fvadmin's passwd: 
Dec 12, 2012 11:08:22 AM org.apache.xmlrpc.server.XmlRpcErrorLogger log
SEVERE: Failed to invoke method deleteSlice in class org.flowvisor.api.FVUserAPIXMLRPCImpl: slice does not exist: Data_plane_testing_slice_ID__openflow_geant_net_ID__192_168_254_193_15.4
org.apache.xmlrpc.common.XmlRpcInvocationException: Failed to invoke method deleteSlice in class org.flowvisor.api.FVUserAPIXMLRPCImpl: slice does not exist: Data_plane_testing_slice_ID__openflow_geant_net_ID__192_168_254_193_15.4
    at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:129)
    at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.execute(ReflectiveXmlRpcHandler.java:106)
    at org.apache.xmlrpc.server.XmlRpcServerWorker.execute(XmlRpcServerWorker.java:46)
    at org.apache.xmlrpc.server.XmlRpcServer.execute(XmlRpcServer.java:86)
    at org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:200)
    at org.apache.xmlrpc.webserver.Connection.run(Connection.java:208)
    at org.apache.xmlrpc.util.ThreadPool$Poolable$1.run(ThreadPool.java:68)
Caused by: org.flowvisor.exceptions.SliceNotFound: slice does not exist: Data_plane_testing_slice_ID__openflow_geant_net_ID__192_168_254_193_15.4
    at org.flowvisor.api.FVUserAPIImpl.deleteSlice(FVUserAPIImpl.java:417)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:115)
    ... 6 more
Caused by:
org.flowvisor.exceptions.SliceNotFound: slice does not exist: Data_plane_testing_slice_ID__openflow_geant_net_ID__192_168_254_193_15.4
    at org.flowvisor.api.FVUserAPIImpl.deleteSlice(FVUserAPIImpl.java:417)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:115)
    at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.execute(ReflectiveXmlRpcHandler.java:106)
    at org.apache.xmlrpc.server.XmlRpcServerWorker.execute(XmlRpcServerWorker.java:46)
    at org.apache.xmlrpc.server.XmlRpcServer.execute(XmlRpcServer.java:86)
    at org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:200)
    at org.apache.xmlrpc.webserver.Connection.run(Connection.java:208)
    at org.apache.xmlrpc.util.ThreadPool$Poolable$1.run(ThreadPool.java:68)
error: org.apache.xmlrpc.XmlRpcException: Failed to invoke method deleteSlice in class org.flowvisor.api.FVUserAPIXMLRPCImpl: slice does not exist: Data_plane_testing_slice_ID__openflow_geant_net_ID__192_168_254_193_15.4
OfeliaSDKr1:~# 
</code>

**Comment by CarolinaFernandez** [comment]
Error was due to that final ".".

However, Opt-in translates the slice names properly and therefore this never happened again after that.
